import {
  ASTROLOGY_CLAIMS,
  EPHEMERIS_CLAIMS,
  INTERNAL_SURFACES,
  MYEONGLI_CLAIMS,
  OUTPUT_SURFACES,
  PRODUCT_CONTRACT_CLAIMS,
  PRODUCT_OUTPUT_SURFACES,
  source,
  type SourceRegistryRecord,
} from './source-registry-types.ts';

export const ASTRO_ZIWEI_SOURCE_REGISTRY = [
  source({
    sourceId: 'ptolemy_tetrabiblos_public_text',
    domain: 'western_astrology',
    sourceRole: 'classical_astrology_doctrine',
    promotionState: 'reviewed_for_limited_use',
    sourceStatus: 'verified_public_text',
    licenseStatus: 'public_domain_candidate',
    runtimeUse: 'blocked_pending_acquisition',
    rightsRuntimeUseStates: ['citation_only'],
    allowedSurfaces: INTERNAL_SURFACES,
    forbiddenSurfaces: [...OUTPUT_SURFACES, 'customer_report_text', 'paid_pdf_text'],
    allowedClaimFamilies: ['classical_planet_sign_doctrine', 'classical_house_topic_doctrine', 'traditional_dignity_doctrine'],
    forbiddenClaimFamilies: ['modern_outer_planet_doctrine', 'modern_psychological_astrology', ...EPHEMERIS_CLAIMS],
    caveat: 'Classical astrology only; no Uranus, Neptune, Pluto, or modern counseling claims.',
    sourceUrlOrLocator: 'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ptolemy/Tetrabiblos/home.html',
    captureStatus: 'candidate',
    reviewStatus: 'needs_expert_review',
    knownBadFixtureIds: ['reject_ptolemy_outer_planet_psychology'],
  }),
  source({
    sourceId: 'modern_astrology_sources_pending',
    domain: 'western_astrology',
    sourceRole: 'modern_astrology_doctrine',
    promotionState: 'rights_review_required',
    sourceStatus: 'blocked_pending_license',
    licenseStatus: 'commercial_license_required',
    runtimeUse: 'blocked_pending_license',
    rightsRuntimeUseStates: ['blocked'],
    allowedSurfaces: ['internal_research'],
    forbiddenSurfaces: PRODUCT_OUTPUT_SURFACES,
    allowedClaimFamilies: ['source_discovery_only'],
    forbiddenClaimFamilies: [...ASTROLOGY_CLAIMS, ...PRODUCT_CONTRACT_CLAIMS],
    caveat: 'Licensed source decision or product-synthesis label required before modern doctrine use.',
    sourceUrlOrLocator: '.omo/drafts/western-astrology-doctrine-acquisition-protocol.md',
    captureStatus: 'pending_acquisition',
    reviewStatus: 'needs_license_review',
    knownBadFixtureIds: ['reject_modern_psychology_without_license_or_synthesis'],
  }),
  source({
    sourceId: 'ziwei_doushu_quanshu_public_text',
    domain: 'ziwei_doushu',
    sourceRole: 'ziwei_canonical_doctrine',
    promotionState: 'reviewed_for_limited_use',
    sourceStatus: 'verified_public_text',
    licenseStatus: 'public_domain_candidate',
    runtimeUse: 'blocked_pending_acquisition',
    rightsRuntimeUseStates: ['citation_only'],
    allowedSurfaces: INTERNAL_SURFACES,
    forbiddenSurfaces: [...OUTPUT_SURFACES, 'customer_report_text', 'paid_pdf_text'],
    allowedClaimFamilies: ['ziwei_12_palaces_meaning', 'ziwei_major_stars_doctrine', 'ziwei_sihua_dynamics', 'ziwei_sanfang_sizheng'],
    forbiddenClaimFamilies: [...MYEONGLI_CLAIMS, ...ASTROLOGY_CLAIMS],
    caveat: 'Canonical 12-palace calculation and star assignment baseline.',
    sourceUrlOrLocator: 'Canonical Ziwei Doushu literature',
    captureStatus: 'candidate',
    reviewStatus: 'needs_expert_review',
    knownBadFixtureIds: ['reject_invented_ziwei_stars'],
  }),
] satisfies readonly SourceRegistryRecord[];
