import {
  ASTROLOGY_CLAIMS,
  EPHEMERIS_CLAIMS,
  INTERNAL_SURFACES,
  MYEONGLI_CLAIMS,
  OUTPUT_SURFACES,
  PRODUCT_CONTRACT_CLAIMS,
  PRODUCT_OUTPUT_SURFACES,
  REPORT_SURFACES,
  TAROT_CLAIMS,
  source,
  type SourceRegistryRecord,
} from './source-registry-types.ts';

export const ASTRO_TAROT_SOURCE_REGISTRY = [
  source({
    sourceId: 'ptolemy_tetrabiblos_public_text',
    domain: 'western_astrology',
    sourceRole: 'classical_astrology_doctrine',
    promotionState: 'reviewed_for_limited_use',
    sourceStatus: 'verified_public_text',
    licenseStatus: 'public_domain_candidate',
    runtimeUse: 'blocked_pending_acquisition',
    rightsRuntimeUseStates: ['citation_only'],
    allowedSurfaces: INTERNAL_SURFACES,
    forbiddenSurfaces: [...OUTPUT_SURFACES, 'customer_report_text', 'paid_pdf_text'],
    allowedClaimFamilies: ['classical_planet_sign_doctrine', 'classical_house_topic_doctrine', 'traditional_dignity_doctrine'],
    forbiddenClaimFamilies: ['modern_outer_planet_doctrine', 'modern_psychological_astrology', ...EPHEMERIS_CLAIMS],
    caveat: 'Classical astrology only; no Uranus, Neptune, Pluto, or modern counseling claims.',
    sourceUrlOrLocator: 'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ptolemy/Tetrabiblos/home.html',
    captureStatus: 'candidate',
    reviewStatus: 'needs_expert_review',
    knownBadFixtureIds: ['reject_ptolemy_outer_planet_psychology'],
  }),
  source({
    sourceId: 'modern_astrology_sources_pending',
    domain: 'western_astrology',
    sourceRole: 'modern_astrology_doctrine',
    promotionState: 'rights_review_required',
    sourceStatus: 'blocked_pending_license',
    licenseStatus: 'commercial_license_required',
    runtimeUse: 'blocked_pending_license',
    rightsRuntimeUseStates: ['blocked'],
    allowedSurfaces: ['internal_research'],
    forbiddenSurfaces: PRODUCT_OUTPUT_SURFACES,
    allowedClaimFamilies: ['source_discovery_only'],
    forbiddenClaimFamilies: [...ASTROLOGY_CLAIMS, ...PRODUCT_CONTRACT_CLAIMS],
    caveat: 'Licensed source decision or product-synthesis label required before modern doctrine use.',
    sourceUrlOrLocator: '.omo/drafts/western-astrology-doctrine-acquisition-protocol.md',
    captureStatus: 'pending_acquisition',
    reviewStatus: 'needs_license_review',
    knownBadFixtureIds: ['reject_modern_psychology_without_license_or_synthesis'],
  }),
  source({
    sourceId: 'waite_pictorial_key_public_text',
    domain: 'tarot',
    sourceRole: 'rws_tarot_doctrine',
    promotionState: 'reviewed_for_limited_use',
    sourceStatus: 'verified_public_text',
    licenseStatus: 'public_domain_candidate',
    runtimeUse: 'blocked_pending_acquisition',
    rightsRuntimeUseStates: ['citation_only'],
    allowedSurfaces: INTERNAL_SURFACES,
    forbiddenSurfaces: [...OUTPUT_SURFACES, 'customer_report_text', 'paid_pdf_text'],
    allowedClaimFamilies: ['rws_major_arcana_meaning', 'rws_minor_arcana_meaning', 'rws_reversed_meaning', 'rws_spread_position_semantics'],
    forbiddenClaimFamilies: ['tarot_image_provenance', ...MYEONGLI_CLAIMS, ...ASTROLOGY_CLAIMS],
    caveat: 'Card-level extraction required; Waite text never clears image rights.',
    sourceUrlOrLocator: 'https://www.gutenberg.org/ebooks/43548',
    captureStatus: 'candidate',
    reviewStatus: 'needs_expert_review',
    knownBadFixtureIds: ['reject_waite_image_as_card_meaning', 'reject_waite_text_as_image_license'],
  }),
  source({
    sourceId: 'waite_pictorial_key_sacred_texts_index',
    domain: 'tarot',
    sourceRole: 'tarot_text_index_discovery',
    promotionState: 'observed_for_discovery',
    sourceStatus: 'verified_candidate',
    licenseStatus: 'unknown',
    runtimeUse: 'discovery_only',
    rightsRuntimeUseStates: ['internal_research_only'],
    allowedSurfaces: INTERNAL_SURFACES,
    forbiddenSurfaces: PRODUCT_OUTPUT_SURFACES,
    allowedClaimFamilies: ['source_discovery_only'],
    forbiddenClaimFamilies: [...TAROT_CLAIMS, ...MYEONGLI_CLAIMS, ...ASTROLOGY_CLAIMS],
    caveat: 'Index locator only; Waite text authority and image rights remain separate.',
    sourceUrlOrLocator: 'https://sacred-texts.com/tarot/pkt/index.htm',
    captureStatus: 'orientation_only',
    reviewStatus: 'needs_expert_review',
    knownBadFixtureIds: ['reject_sacred_texts_index_as_text_authority', 'reject_sacred_texts_index_as_image_license'],
  }),
  source({
    sourceId: 'rws_tarot_baseline',
    domain: 'tarot',
    sourceRole: 'tarot_deck_policy',
    promotionState: 'candidate_captured',
    sourceStatus: 'verified_candidate',
    licenseStatus: 'not_applicable',
    runtimeUse: 'policy_only',
    rightsRuntimeUseStates: ['citation_only'],
    allowedSurfaces: INTERNAL_SURFACES,
    forbiddenSurfaces: PRODUCT_OUTPUT_SURFACES,
    allowedClaimFamilies: ['rws_deck_identity_policy'],
    forbiddenClaimFamilies: [...MYEONGLI_CLAIMS, ...ASTROLOGY_CLAIMS, 'tarot_image_provenance'],
    caveat: 'Deck identity policy only; it approves no card meaning or visual asset by itself.',
    sourceUrlOrLocator: '.omo/drafts/tarot-rws-78-corpus-blueprint.md',
    captureStatus: 'candidate',
    reviewStatus: 'needs_expert_review',
    knownBadFixtureIds: ['reject_marseille_or_thoth_inside_rws_v1'],
  }),
  source({
    sourceId: 'rws_card_images_commons_candidate',
    domain: 'tarot',
    sourceRole: 'tarot_visual_asset_candidate',
    promotionState: 'rights_review_required',
    sourceStatus: 'verified_candidate',
    licenseStatus: 'unknown',
    runtimeUse: 'blocked_pending_acquisition',
    rightsRuntimeUseStates: ['internal_research_only'],
    allowedSurfaces: INTERNAL_SURFACES,
    forbiddenSurfaces: [...REPORT_SURFACES, ...OUTPUT_SURFACES],
    allowedClaimFamilies: ['tarot_image_provenance'],
    forbiddenClaimFamilies: ['rws_major_arcana_meaning', 'rws_minor_arcana_meaning', 'rws_reversed_meaning', 'rws_spread_position_semantics'],
    caveat: 'Commons category is not file-level paid-PDF clearance; exact file audit required.',
    sourceUrlOrLocator: 'Wikimedia Commons RWS image candidate category/file records',
    captureStatus: 'candidate',
    reviewStatus: 'needs_license_review',
    knownBadFixtureIds: ['reject_commons_category_as_paid_pdf_license', 'reject_one_commons_file_as_all_card_license'],
  }),
] satisfies readonly SourceRegistryRecord[];
