import {
  ASTROLOGY_CLAIMS,
  EPHEMERIS_CLAIMS,
  FIXTURE_SURFACES,
  MYEONGLI_CLAIMS,
  PRODUCT_OUTPUT_SURFACES,
  REPORT_AUTHORITY_CLAIMS,
  TAROT_CLAIMS,
  source,
  type SourceRegistryRecord,
} from './source-registry-types.ts';

function calculationSource(
  sourceId: string,
  allowedClaimFamilies: readonly string[],
  sourceUrlOrLocator: string,
  knownBadFixtureIds: readonly string[]
): SourceRegistryRecord {
  return source({
    sourceId,
    domain: 'calendar_astronomy',
    sourceRole: 'calendar_calculation',
    promotionState: 'approved_for_fixture',
    sourceStatus: 'verified_validation',
    licenseStatus: 'not_applicable',
    runtimeUse: 'validation_only',
    rightsRuntimeUseStates: ['fixture_only', 'citation_only'],
    allowedSurfaces: FIXTURE_SURFACES,
    forbiddenSurfaces: PRODUCT_OUTPUT_SURFACES,
    allowedClaimFamilies,
    forbiddenClaimFamilies: REPORT_AUTHORITY_CLAIMS,
    caveat: 'Calculation/almanac source only; never doctrine or life-domain interpretation.',
    sourceUrlOrLocator,
    captureStatus: 'captured',
    reviewStatus: 'approved_for_fixtures',
    knownBadFixtureIds,
  });
}

const KASI_SOURCES = [
  ['kasi_lunisolar_conversion', ['solar_lunar_conversion', 'julian_gregorian_policy'], 'https://astro.kasi.re.kr/life/pageView/5', ['reject_kasi_as_yongsin_doctrine', 'reject_kasi_as_career_love_doctrine']],
  ['kasi_open_api', ['solar_lunar_conversion', 'korean_calendar_almanac', 'solar_term_fixture'], 'https://astro.kasi.re.kr/', ['reject_kasi_api_as_interpretation_doctrine', 'reject_kasi_as_ten_gods_source']],
  ['kasi_almanac', ['korean_calendar_almanac', 'solar_term_fixture'], 'https://astro.kasi.re.kr/life/pageView/6', ['reject_kasi_almanac_as_gyeokguk_source']],
] as const;

export const CALCULATION_SOURCE_REGISTRY = [
  ...KASI_SOURCES.map(([sourceId, claims, locator, fixtures]) => calculationSource(sourceId, claims, locator, fixtures)),
  source({
    sourceId: 'jpl_horizons',
    domain: 'western_astrology',
    sourceRole: 'western_ephemeris',
    promotionState: 'approved_for_fixture',
    sourceStatus: 'verified_validation',
    licenseStatus: 'internal_reference_only',
    runtimeUse: 'validation_only',
    rightsRuntimeUseStates: ['fixture_only', 'citation_only'],
    allowedSurfaces: FIXTURE_SURFACES,
    forbiddenSurfaces: PRODUCT_OUTPUT_SURFACES,
    allowedClaimFamilies: ['planetary_longitude_fixture', 'moon_position_fixture'],
    forbiddenClaimFamilies: [...MYEONGLI_CLAIMS, ...ASTROLOGY_CLAIMS, ...TAROT_CLAIMS],
    caveat: 'Ephemeris validation only; never astrology meaning or personality interpretation.',
    sourceUrlOrLocator: 'https://ssd.jpl.nasa.gov/horizons/',
    captureStatus: 'captured',
    reviewStatus: 'approved_for_fixtures',
    knownBadFixtureIds: ['reject_jpl_as_interpretation', 'reject_jpl_as_astrology_meaning'],
  }),
  source({
    sourceId: 'jpl_horizons_api',
    domain: 'western_astrology',
    sourceRole: 'western_ephemeris',
    promotionState: 'approved_for_fixture',
    sourceStatus: 'verified_validation',
    licenseStatus: 'internal_reference_only',
    runtimeUse: 'validation_only',
    rightsRuntimeUseStates: ['fixture_only', 'citation_only'],
    allowedSurfaces: FIXTURE_SURFACES,
    forbiddenSurfaces: PRODUCT_OUTPUT_SURFACES,
    allowedClaimFamilies: EPHEMERIS_CLAIMS,
    forbiddenClaimFamilies: [...MYEONGLI_CLAIMS, ...ASTROLOGY_CLAIMS, ...TAROT_CLAIMS],
    caveat: 'API parameters, time scale, observer frame, and tolerance must be captured.',
    sourceUrlOrLocator: 'https://ssd-api.jpl.nasa.gov/doc/horizons.html',
    captureStatus: 'candidate',
    reviewStatus: 'approved_for_fixtures',
    knownBadFixtureIds: ['reject_jpl_api_as_personality_source'],
  }),
  source({
    sourceId: 'swiss_ephemeris',
    domain: 'western_astrology',
    sourceRole: 'western_ephemeris',
    promotionState: 'rights_review_required',
    sourceStatus: 'blocked_pending_license',
    licenseStatus: 'commercial_license_required',
    runtimeUse: 'blocked_pending_license',
    rightsRuntimeUseStates: ['blocked'],
    allowedSurfaces: ['source_provenance_appendix'],
    forbiddenSurfaces: PRODUCT_OUTPUT_SURFACES,
    allowedClaimFamilies: EPHEMERIS_CLAIMS,
    forbiddenClaimFamilies: REPORT_AUTHORITY_CLAIMS,
    caveat: 'AGPL/commercial license decision required before public service or server runtime.',
    sourceUrlOrLocator: 'https://www.astro.com/swisseph/',
    captureStatus: 'candidate',
    reviewStatus: 'needs_license_review',
    knownBadFixtureIds: ['reject_swiss_runtime_without_license', 'reject_swiss_runtime_before_license'],
  }),
] satisfies readonly SourceRegistryRecord[];
