import {
  DOCTRINE_CLAIMS,
  OUTPUT_SURFACES,
  PRODUCT_CONTRACT_CLAIMS,
  REPORT_SURFACES,
  SAFETY_CLAIMS,
  source,
  type SourceRegistryRecord,
} from './source-registry-types.ts';

export const PRODUCT_SOURCE_REGISTRY = [
  source({
    sourceId: 'cosmicpath_divination_safety_policy',
    domain: 'product_safety',
    sourceRole: 'product_safety_policy',
    promotionState: 'approved_for_product_policy',
    sourceStatus: 'verified_candidate',
    licenseStatus: 'not_applicable',
    runtimeUse: 'allowed',
    rightsRuntimeUseStates: ['customer_prose_allowed'],
    allowedSurfaces: [...REPORT_SURFACES, 'source_provenance_appendix'],
    forbiddenSurfaces: OUTPUT_SURFACES,
    allowedClaimFamilies: SAFETY_CLAIMS,
    forbiddenClaimFamilies: DOCTRINE_CLAIMS,
    caveat: 'Safety policy restricts claims; it never proves divination doctrine.',
    sourceUrlOrLocator: '.omo/drafts/divination-safety-claim-boundaries.md',
    captureStatus: 'captured',
    reviewStatus: 'approved_for_product_policy',
    knownBadFixtureIds: ['reject_safety_policy_as_doctrine_source', 'reject_safety_policy_as_doctrine'],
  }),
  source({
    sourceId: 'cosmicpath_report_grounding_contract',
    domain: 'cross_domain',
    sourceRole: 'report_grounding_contract',
    promotionState: 'approved_for_product_policy',
    sourceStatus: 'verified_candidate',
    licenseStatus: 'not_applicable',
    runtimeUse: 'allowed',
    rightsRuntimeUseStates: ['customer_prose_allowed'],
    allowedSurfaces: [...REPORT_SURFACES, 'source_provenance_appendix'],
    forbiddenSurfaces: OUTPUT_SURFACES,
    allowedClaimFamilies: PRODUCT_CONTRACT_CLAIMS,
    forbiddenClaimFamilies: DOCTRINE_CLAIMS,
    caveat: 'Grounding contract structures output; paragraphs still need computed facts and source/rule anchors.',
    sourceUrlOrLocator: '.omo/drafts/report-grounding-contract-blueprint.md',
    captureStatus: 'captured',
    reviewStatus: 'approved_for_product_policy',
    knownBadFixtureIds: ['reject_source_like_prose_no_ids', 'reject_product_synthesis_as_only_doctrine_support'],
  }),
] satisfies readonly SourceRegistryRecord[];
